{
    ("features.0", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.0.weight", experiment_state=current_state),
    ("features.0", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.0.bias", experiment_state=current_state),
    ("features.3", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.3.weight", experiment_state=current_state),
    ("features.3", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.3.bias", experiment_state=current_state),
    ("features.6", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.6.weight", experiment_state=current_state),
    ("features.6", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.6.bias", experiment_state=current_state),
    ("features.8", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.8.weight", experiment_state=current_state),
    ("features.8", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.8.bias", experiment_state=current_state),
    ("features.10", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.10.weight", experiment_state=current_state),
    ("features.10", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.10.bias", experiment_state=current_state),
    ("classifier.1", "weight"): partial(initializations.rewind_initialization, 
        param_name="classifier.1.weight", experiment_state=current_state),
    ("classifier.1", "bias"): partial(initializations.rewind_initialization, 
        param_name="classifier.1.bias", experiment_state=current_state),
    ("classifier.4", "weight"): partial(initializations.rewind_initialization, 
        param_name="classifier.4.weight", experiment_state=current_state),
    ("classifier.4", "bias"): partial(initializations.rewind_initialization, 
        param_name="classifier.4.bias", experiment_state=current_state),
    ("classifier.6", "weight"): partial(initializations.rewind_initialization, 
        param_name="classifier.6.weight", experiment_state=current_state),
    ("classifier.6", "bias"): partial(initializations.rewind_initialization, 
        param_name="classifier.6.bias", experiment_state=current_state),
}
