{
    ("features.0", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.0.weight", experiment_state=current_state),
    ("features.3", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.3.weight", experiment_state=current_state),
    ("features.6", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.6.weight", experiment_state=current_state),
    ("features.8", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.8.weight", experiment_state=current_state),
    ("features.11", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.11.weight", experiment_state=current_state),
    ("features.13", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.13.weight", experiment_state=current_state),
    ("features.16", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.16.weight", experiment_state=current_state),
    ("features.18", "weight"): partial(initializations.rewind_initialization, 
        param_name="features.18.weight", experiment_state=current_state),
    ("classifier.0", "weight"): partial(initializations.rewind_initialization, 
        param_name="classifier.0.weight", experiment_state=current_state),
    ("classifier.3", "weight"): partial(initializations.rewind_initialization, 
        param_name="classifier.3.weight", experiment_state=current_state),
    ("classifier.6", "weight"): partial(initializations.rewind_initialization, 
        param_name="classifier.6.weight", experiment_state=current_state),
    ("features.0", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.0.bias", experiment_state=current_state),
    ("features.3", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.3.bias", experiment_state=current_state),
    ("features.6", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.6.bias", experiment_state=current_state),
    ("features.8", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.8.bias", experiment_state=current_state),
    ("features.11", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.11.bias", experiment_state=current_state),
    ("features.13", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.13.bias", experiment_state=current_state),
    ("features.16", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.16.bias", experiment_state=current_state),
    ("features.18", "bias"): partial(initializations.rewind_initialization, 
        param_name="features.18.bias", experiment_state=current_state),
    ("classifier.0", "bias"): partial(initializations.rewind_initialization, 
        param_name="classifier.0.bias", experiment_state=current_state),
    ("classifier.3", "bias"): partial(initializations.rewind_initialization, 
        param_name="classifier.3.bias", experiment_state=current_state),
    ("classifier.6", "bias"): partial(initializations.rewind_initialization, 
        param_name="classifier.6.bias", experiment_state=current_state),
}
