{
    ("conv1", "weight"): partial(initializations.rewind_initialization, 
        param_name="conv1.weight", experiment_state=current_state),
    ("conv1", "bias"): partial(initializations.rewind_initialization, 
        param_name="conv1.bias", experiment_state=current_state),
    ("conv2", "weight"): partial(initializations.rewind_initialization, 
        param_name="conv2.weight", experiment_state=current_state),
    ("conv2", "bias"): partial(initializations.rewind_initialization, 
        param_name="conv2.bias", experiment_state=current_state),
    ("fc1", "weight"): partial(initializations.rewind_initialization, 
        param_name="fc1.weight", experiment_state=current_state),
    ("fc1", "bias"): partial(initializations.rewind_initialization, 
        param_name="fc1.bias", experiment_state=current_state),
    ("fc2", "weight"): partial(initializations.rewind_initialization, 
        param_name="fc2.weight", experiment_state=current_state),
    ("fc2", "bias"): partial(initializations.rewind_initialization, 
        param_name="fc2.bias", experiment_state=current_state),
    ("fc3", "weight"): partial(initializations.rewind_initialization, 
        param_name="fc3.weight", experiment_state=current_state),
    ("fc3", "bias"): partial(initializations.rewind_initialization, 
        param_name="fc3.bias", experiment_state=current_state),
}
